Adding support for libcurl version 7.4
Azure/azure-sdk-for-cpp pull request #1171
Opened 2020-12-14 18:56 UTC by vhvb1989

fixes: https://github.com/Azure/azure-sdk-for-cpp/issues/1170

2020-12-14 20:05 UTC, ahsonkhan commented on sdk/core/azure-core/CMakeLists.txt
> +set(CURL_MIN_REQUIRED_VERSION 7.4)
Based on offline discussion, we don't want to set the minimum required to a version from 2000, which is too old for the distros we support anyway (like Ubuntu 16.04).
https://curl.se/docs/releases.html

Leave it as 7.44, and let's re-evaluate if we should bump it up even higher.

2020-12-14 20:05 UTC, ahsonkhan requested changes
Based on offline discussion, we don't want to set the minimum required to a version from 2000, which is too old for the distros we support anyway (like Ubuntu 16.04).
https://curl.se/docs/releases.html

Leave it as 7.44, and let's re-evaluate if we should bump it up even higher.

2020-12-14 23:16 UTC, antkmsft requested changes
cmake defined macros don't work in headers. Try to avoid them regardless. Prefix macros with `AZ_`, so users are free to get the rest of the names defined as they want without interfering with our macros and vice versa.

2020-12-14 23:16 UTC, antkmsft commented on sdk/core/azure-core/CMakeLists.txt
> +  add_compile_definitions(BUILD_SSL_OPTION_NO_REVOKE)
1. Prefix with AZ_, especially when the stuff goes into headers.
2. Even if you prefix with AZ_, when users include the file, they won't have `BUILD_SSL_OPTION_NO_REVOKE` defined when they include the header, so the idea won't work. See if you can get this moved into cpp, or if CURL defines its version as a macro, so you can make an `#ifdef` in the code, not in cmake.

2020-12-15 00:15 UTC, vhvb1989 commented
Closing as not to be implemented after reviewing it on stand up meeting. See previous comments for more info

2020-12-15 00:15 UTC, closed without merging