Check if error during test after opening a file
Azure/azure-sdk-for-cpp pull request #1205
Opened 2020-12-17 22:55 UTC by vhvb1989

fixes: #1074

2020-12-17 23:33 UTC, ahsonkhan commented
Need to fix this instance as well, which is where the original issue came from:
https://github.com/Azure/azure-sdk-for-cpp/blob/674a8b623a4ba86172b481af6e63a59cac1612a2/sdk/core/azure-core/test/e2e/azure_core_with_curl_bodyBuffer.cpp#L83-L84

https://github.com/Azure/azure-sdk-for-cpp/pull/1070#discussion_r535383111

2020-12-17 23:34 UTC, ahsonkhan approved these changes
Other than making a similar fix in `azure_core_with_curl_bodyBuffer.cpp`, looks good.

2020-12-18 02:50 UTC, ahsonkhan commented on sdk/core/azure-core/test/e2e/azure_core_with_curl_bodyBuffer.cpp
>    int fd = open("/home/vivazqu/workspace/a", O_RDONLY);
Btw, hardcoding a local file path specific to your machine isn't great. We should fix this.

2020-12-18 02:52 UTC, ahsonkhan commented on sdk/core/azure-core/test/e2e/azure_core_with_curl_bodyBuffer.cpp
> +  //
Running tests and samples shouldn't require manual artifact creation on the machine. Especially not in directories external to the repo.

The test should create whatever file or directory it needs within the sub-folder inside the repo and use it.

2020-12-18 02:53 UTC, ahsonkhan requested changes
Fix the e2e sample/test so that it is runnable on anyone's machine or remove it if not needed or useful.

Alternatively, leave it untouched in this PR, if you feel it is out of scope (and only fix the adapter test), and address it separately. Up to you.

2020-12-18 07:05 UTC, vhvb1989 commented
> Fix the e2e sample/test so that it is runnable on anyone's machine or remove it if not needed or useful.
> 
> Alternatively, leave it untouched in this PR, if you feel it is out of scope (and only fix the adapter test), and address it separately. Up to you.

removing e2e. https://github.com/Azure/azure-sdk-for-cpp/issues/1214

2020-12-18 18:42 UTC, ahsonkhan approved these changes

2020-12-18 18:42 UTC, merged