Token: use DateTime
Azure/azure-sdk-for-cpp pull request #1221
Opened 2020-12-18 13:45 UTC by antkmsft

Closes #1177

2020-12-18 19:21 UTC, ahsonkhan requested changes
Add tests

Avoid merging the default ctor change with this, especially since you already have a separate PR for it (which is blocked for adding tests - https://github.com/Azure/azure-sdk-for-cpp/pull/1220), but otherwise, looks good.

2020-12-18 22:02 UTC, vhvb1989 commented
/azp run cpp - core - ci

2020-12-19 00:29 UTC, antkmsft commented
@ahsonkhan , tests are covered by #271.  I know the separate PR will take care of it, I just have this work done, and this PR will go after the Default constructor PR, after I rebase, and it will be only the DateTime changes.

2020-12-19 02:54 UTC, ahsonkhan approved these changes

2020-12-19 03:10 UTC, merged