extensible enum for blob servicve
Azure/azure-sdk-for-cpp pull request #1253
Opened 2020-12-31 02:06 UTC by Jinming-Hu

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2020-12-31 02:09 UTC, Jinming-Hu commented
/azp run cpp - storage

2021-01-02 08:57 UTC, katmsft commented
/azp run cpp - storage

2021-01-02 10:25 UTC, katmsft commented on sdk/storage/azure-storage-blobs/CMakeLists.txt
> +	src/blob_rest_client.cpp
tab?

2021-01-02 12:54 UTC, katmsft requested changes
Please fix CI.

2021-01-02 13:53 UTC, Jinming-Hu commented on sdk/storage/azure-storage-blobs/CMakeLists.txt
> +	src/blob_rest_client.cpp
```suggestion
    src/blob_rest_client.cpp
```

2021-01-05 02:25 UTC, katmsft approved these changes

2021-01-05 17:06 UTC, merged