Make cmake modules consistent names
Azure/azure-sdk-for-cpp pull request #1498
Opened 2021-01-27 22:36 UTC by vhvb1989

fixes: #1355 

I don't think this is required to be mentioned in the change log.

2021-01-27 23:16 UTC, RickWinter approved these changes

2021-01-27 23:44 UTC, ahsonkhan requested changes
Fixup cmakelist and update the name for the new module.

2021-01-27 23:44 UTC, ahsonkhan commented on CMakeLists.txt
> +include(AzureGlobalCompileOptions)
This doesn't seem like the right include. We are including AGCO twice.

2021-01-27 23:44 UTC, ahsonkhan commented on CMakeLists.txt
> +include(AzureGlobalCompileOptions)
```suggestion
include(AzureDoxygen)
```

2021-01-27 23:44 UTC, ahsonkhan commented on sdk/core/azure-core/CMakeLists.txt
> +include(AzureVcpkg)
Missed the newly added `download_test_data.cmake` - PascalCase it. Also, let's add `Json` in the name.

@RickWinter do we want to prefix cmake modules that came from external sources with `Azure` as well (so `AzureDownloadJsonTestData`?

2021-01-27 23:45 UTC, ahsonkhan commented
> I don't think this is required to be mentioned in the change log.

I agree. But to be certain, can you verify that we don't mention these in any markdown docs and that customers are not meant to include or call these directly in their projects or builds. If both those are true, no need for a CL entry since it isn't useful for the end-user.

2021-01-28 01:36 UTC, vhvb1989 commented
/azp run cpp - core

2021-01-28 01:46 UTC, ahsonkhan approved these changes

2021-01-28 02:55 UTC, merged