Check headers that could be missing when getting blob container properties
Azure/azure-sdk-for-cpp pull request #1707
Opened 2021-02-19 20:33 UTC by volatilevar

When sending a get blob container properties request using [Azurite](url), azure-storage-blob library crashes. Upon debugging, I found the response does not contain "x-ms-default-encryption-scope" or "x-ms-deny-encryption-scope-override" headers. I think it is helpful to check these headers before getting the value.

Below is the response:
(gdb) p httpResponse
$2 = (Azure::Core::Http::RawResponse &) @0x7f35645d1bf0: {m_majorVersion = 1, m_minorVersion = 1, m_statusCode = Azure::Core::Http::HttpStatusCode::Ok, m_reasonPhrase = "OK", m_headers = std::map with 12 elements = {["connection"] = "keep-alive",
    ["date"] = "Fri, 19 Feb 2021 01:13:17 GMT", ["etag"] = "\"0x2380243DA88F140\"", ["last-modified"] = "Fri, 19 Feb 2021 01:13:17 GMT", ["server"] = "Azurite-Blob/3.8.0", ["x-ms-client-request-id"] = "5088c48e-95d0-42a4-7084-ae7854ffedf8",
    ["x-ms-has-immutability-policy"] = "false", ["x-ms-has-legal-hold"] = "false", ["x-ms-lease-state"] = "available", ["x-ms-lease-status"] = "unlocked", ["x-ms-request-id"] = "9a23c5e5-0daf-4384-a1c1-0d1706781f75", ["x-ms-version"] = "2019-12-12"},
  m_bodyStream = std::unique_ptr<Azure::Core::Http::BodyStream> = {get() = 0x0}, m_body = std::vector of length 0, capacity 8192}

2021-02-19 22:51 UTC, vhvb1989 commented on sdk/storage/azure-storage-blobs/inc/azure/storage/blobs/protocol/blob_rest_client.hpp
> +          }
This code is auto-generated. Please let @Jinming-Hu  to take a look and update the generator if required.

2021-02-20 01:22 UTC, Jinming-Hu commented
Hi @volatilevar, thanks for reporting this issue. When you say _sending a get blob container properties request using Azurite_, did you mean running this storage sdk against Azurite? So the request was sent to Azurite server?

2021-02-20 01:22 UTC, Jinming-Hu requested changes
Cannot modify auto-generated code directly, should modify auto-generator

2021-02-20 03:34 UTC, Jinming-Hu commented
close in favor of https://github.com/Azure/azure-sdk-for-cpp/pull/1714

2021-02-20 03:34 UTC, closed without merging