Add second template project
Azure/azure-sdk-for-cpp pull request #1735
Opened 2021-02-25 05:34 UTC by danieljurek

The purpose of this project is to validate that we don't break the atomic vcpkg shipping scenario where multiple packages release in the same PR. Without this package we cannot meaningfully validate the atomic process in a way that doesn't cause packages (like `azure-core`) to be released (potentially multiple times). 

If we don't add this to the repo then it'll have to be added into nearly any branch which alters the release steps and then backed out. 

I'm open to changing the name from `azure-template-second` to something more like `azure-template-releasetester` or something which better describes its purpose.

2021-02-25 05:36 UTC, danieljurek commented
@ahsonkhan -- you had some feedback back when I tried to sneak this in as part of another PR. 

@RickWinter -- your feedback here would also be appreciated given we're adding another package (intended to be used for testing only)

2021-02-25 16:23 UTC, ahsonkhan commented
> I'm open to changing the name from `azure-template-second` to something more like `azure-template-releasetester` or something which better describes its purpose. 

Good idea. I am for it.

> If we don't add this to the repo then it'll have to be added into nearly any branch which alters the release steps and then backed out. 

How common would such release edits be, specific to the vcpkg release step? I am wondering how valuable this check will be going forward in actually guaranteeing successful releases of multiple packages, trading off against the extra "fluff" and noise to the repo its adding. Especially because we probably won't ship multiple packages in the same release pipeline step all that often. Maybe this could be an ad-hoc validation instead?

2021-02-25 17:35 UTC, RickWinter requested changes

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/CMakeLists.txt
> +add_subdirectory(azure-template-second)
I don't have a strong preference on the name.  Maybe `engsys-testpkg` or `azure-engsys-testpkg`.  Something to make clear this package in about validating automation and should not be cloned as the starting point for client library authors.

```suggestion
add_subdirectory(azure-template-second)

```

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/inc/azure/template/second/dll_import_export.hpp
> +#if defined(AZ_TEMPLATE_DLL) || (0 /*@AZ_TEMPLATE_DLL_INSTALLED_AS_PACKAGE@*/)
There MACROS need to be named specific to the package name you choose.  i.e.
```suggestion
#if defined(AZ_TEMPLATE_SECOND_DLL) || (0 /*@AZ_TEMPLATE_SECOND_DLL_INSTALLED_AS_PACKAGE@*/)
```

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/inc/azure/template/second/dll_import_export.hpp
> +#define AZ_TEMPLATE_DLLEXPORT __declspec(dllexport)
ditto on all this and the unique name to the package

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/inc/azure/template/second/template_client.hpp
> +}}} // namespace Azure::Template::Second
```suggestion
}}} // namespace Azure::Template::Second

```

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/inc/azure/template/second/version.hpp
> +#define AZURE_TEMPLATE_VERSION_PRERELEASE "beta.30"
This should start at beta.1

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/vcpkg/CONTROL
> +Build-Depends: azure-core-cpp
Is this meant to only depend on core?  I thought template second was a dependency on template.

2021-02-25 17:35 UTC, RickWinter commented on sdk/template/azure-template-second/vcpkg/CONTROL
> +Homepage: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/template/azure-template
Update link to the package name once you decide on the name
```suggestion
Homepage: https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/template/azure-template-second
```

2021-02-25 19:10 UTC, danieljurek commented
@ahsonkhan and I discussed this today and have come to the conclusion that this kind of testing could be a subset of tests we want to run periodically to ensure we aren't failing vcpkg CI. 

To that end it might be best to keep this in its own branch and use it to validate changes to vcpkg release until we can build the periodic vcpkg verification. Any such verification would have to use the exact same vcpkg release steps to ensure proper test coverage.

2021-03-03 16:02 UTC, RickWinter commented
@danieljurek You mention you are going with a different approach.  Should this PR be closed?

2021-03-08 18:07 UTC, danieljurek commented
Closing this PR as we are taking a different approach.

2021-03-08 18:07 UTC, closed without merging