Http request counter
Azure/azure-sdk-for-cpp pull request #1738
Opened 2021-02-25 07:56 UTC by vhvb1989

fixes: #1337 

- Move StartTry to private.
- Adding GetRetryCount().

2021-02-25 08:15 UTC, Jinming-Hu commented on sdk/core/azure-core/inc/azure/core/http/http.hpp
> +    uint GetRetryCount() const { return m_retryCount; }
```suggestion
    int GetRetryCount() const { return m_retryCount; }
```

2021-02-25 08:15 UTC, Jinming-Hu commented on sdk/core/azure-core/inc/azure/core/http/http.hpp
> +    uint m_retryCount = 0;
```suggestion
    int m_retryCount = 0;
```

2021-02-25 17:53 UTC, RickWinter requested changes
The original issue this fixes needs more details into the problem we are fixing.

2021-02-26 07:37 UTC, vhvb1989 commented
> The original issue this fixes needs more details into the problem we are fixing.

Other languages uses a `RequestContext` object to share one state across the pipeline.
This feature is require to implement a policy that reacts to some of the output of a previous policy. For example, the `StorageSwitchServerPolicy` needs to know if the request is on retry mode or not in order to switch to a second server.

I consider adding the entire RequestContext object as a map<string, string> to allow any state to be recorded, but this becomes more expensive for what we currently need right now ( just one int value)

2021-02-26 21:20 UTC, ahsonkhan commented
> I consider adding the entire RequestContext object as a map<string, string> to allow any state to be recorded, but this becomes more expensive for what we currently need right now ( just one int value)

Are we sure we won't need to add more context info across different retries in the future? Having a struct wrapping the int allows us to be more extensible in the future without having to make breaking changes.

2021-02-26 21:58 UTC, vhvb1989 commented
> Are we sure we won't need to add more context info across different retries in the future? 

Just for now. God knows about the future hahahha..  But, if the future comes, the approach would be to keep adding the state as private fields in the request.  I think this is more efficient for C++ than a generic `map<string, T>`

2021-02-26 23:53 UTC, vhvb1989 commented
Use Azure Core context

2021-03-01 22:15 UTC, vhvb1989 commented
/azp run cpp - keyvault

2021-03-01 22:15 UTC, vhvb1989 commented
/azp run cpp - storage

2021-03-01 22:27 UTC, vhvb1989 commented
@Jinming-Hu  After reviewing this solution with Azure Core team, we decided to use the Context to keep the retry number information.
Please use `Azure::Core::Http::RetryProlicy::GetRetryNumber(Context)` to know about the retry number from the context.

The retry policy will update the value on each retry

2021-03-02 01:36 UTC, Jinming-Hu commented
> @Jinming-Hu After reviewing this solution with Azure Core team, we decided to use the Context to keep the retry number information.
> Please use `Azure::Core::Http::RetryProlicy::GetRetryNumber(Context)` to know about the retry number from the context.
> 
> The retry policy will update the value on each retry

I don't see any problem in this way. So it works for me. We may need to merge other PRs first.

2021-03-03 17:59 UTC, RickWinter approved these changes

2021-03-03 17:59 UTC, RickWinter commented on sdk/core/azure-core/src/http/retry_policy.cpp
> +static constexpr char RetryKey[] = "azureSdkRetryPolicyCounter";
```suggestion
static constexpr char RetryKey[] = "AzureSdkRetryPolicyCounter";
```

2021-03-03 17:59 UTC, RickWinter commented on sdk/core/azure-core/src/http/retry_policy.cpp
> +Context inline GetRetryContext(Context const& parent)
```suggestion
Context inline CreateRetryContext(Context const& parent)
```

2021-03-03 17:59 UTC, RickWinter commented on sdk/core/azure-core/src/http/retry_policy.cpp
> +    return 0;
Document that 0 implies no RetyPolicy is present.

2021-03-03 17:59 UTC, RickWinter commented on sdk/core/azure-core/src/http/retry_policy.cpp
> +    return 0;
-1 is a better sentinel

2021-03-03 20:51 UTC, merged