Remove Type suffix from some enums.
Azure/azure-sdk-for-cpp pull request #1951
Opened 2021-03-22 06:05 UTC by katmsft

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/master/CONTRIBUTING.md#pull-requests).

- [x] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [x] Doxygen docs
- [x] Unit tests
- [x] No unwanted commits/changes
- [x] Descriptive title/description
  - [x] PR is single purpose
  - [x] Related issue listed
- [x] Comments in source
- [x] No typos
- [x] Update changelog
- [x] Not work-in-progress
- [x] External references or docs updated
- [x] Self review of PR done
- [x] Any breaking changes?

2021-03-22 06:05 UTC, katmsft commented
/azp run cpp - storage

2021-03-22 06:09 UTC, katmsft commented
/azp run cpp - storage

2021-03-22 07:38 UTC, Jinming-Hu commented
Where is `DataLake::Models::PathExpiryOptions` used?

2021-03-22 07:45 UTC, Jinming-Hu requested changes
see in comment

2021-03-22 07:46 UTC, Jinming-Hu commented
@danieljurek CI seems to be down, can you take a look?

2021-03-22 08:31 UTC, Jinming-Hu approved these changes

2021-03-22 08:44 UTC, katmsft commented
/azp run cpp - storage

2021-03-22 09:01 UTC, katmsft commented
/azp run cpp - storage

2021-03-22 18:48 UTC, danieljurek commented
@Jinming-Hu, @katmsft  -- Thanks for re-running the pipeline. This was caused by an issue on the Engineering System side that we have resolved. Re-running the pipeline should succeed now.

2021-03-22 18:48 UTC, danieljurek commented
/azp run cpp - storage

2021-03-22 21:43 UTC, ahsonkhan commented
/azp run cpp - storage

2021-03-22 22:16 UTC, ahsonkhan commented
@danieljurek new intermittent infra failure on MacOS during test resource deployment:
https://dev.azure.com/azure-sdk/internal/_build/results?buildId=796737&view=logs&j=267db408-59fc-59d9-cfd0-fd1515cbe21c&t=ef2413d8-cecc-5056-5cea-ca63a0346a44&l=10357
```text
Write-Error: /Users/runner/work/1/s/eng/common/TestResources/New-TestResources.ps1:412
Line |
 412 |          $deployment = Retry {
     |                        ~~~~~~~
     | Exception calling "Invoke" with "0" argument(s): "The running
     | command stopped because the preference variable
     | "ErrorActionPreference" or common parameter is set to Stop:
     | 9:58:53 PM - The deployment 'tb8792f0a8ce54c5e' failed with
     | error(s). Showing 1 out of 1 error(s). Status Message: A hash
     | conflict was encountered for the role Assignment ID. Please
     | use a new Guid.
     | (Code:HashConflictOnDifferentRoleAssignmentIds) 
     | CorrelationId: 6499df0b-227d-4129-bb0e-71b940b1c7d2
```

2021-03-22 22:55 UTC, ahsonkhan commented on sdk/storage/azure-storage-files-shares/CHANGELOG.md
> +- Renamed `ListSharesIncludeType` to `ListSharesIncludeFlags`.
For enums, when do we decide to use the "Flags" suffix, vs not?

2021-03-22 22:56 UTC, ahsonkhan approved these changes

2021-03-22 23:20 UTC, merged

2021-03-23 04:25 UTC, danieljurek commented
Thanks @ahsonkhan, we've seen this issue before here: https://github.com/Azure/azure-sdk-tools/issues/1240 ... It seems to show up from time to time. 

The template is well formed to create unique assignment names and while re-running will likely fix the issue there may be some more we can do to help fix this. I'm not sure if the role assignment needs to be unique to the resource, group, subscription, or at some other level (like globally).