update changelog for release - Storage - Beta10
Azure/azure-sdk-for-cpp pull request #2006
Opened 2021-03-30 23:20 UTC by vhvb1989

2021-03-30 23:43 UTC, Jinming-Hu approved these changes

2021-04-01 16:15 UTC, RickWinter requested changes
Might be best to abandon this change let Storage make it when they release next week.

2021-04-01 16:15 UTC, RickWinter commented on sdk/storage/azure-storage-blobs/CHANGELOG.md
> +## 12.0.0-beta.10 (2021-03-30)
```suggestion
## 12.0.0-beta.10 (2021-04-06)
```

2021-04-01 16:15 UTC, RickWinter commented on sdk/storage/azure-storage-common/CHANGELOG.md
> +## 12.0.0-beta.10 (2021-03-30)
```suggestion
## 12.0.0-beta.10 (2021-04-06)
```

2021-04-01 16:15 UTC, RickWinter commented on sdk/storage/azure-storage-files-datalake/CHANGELOG.md
> +## 12.0.0-beta.10 (2021-03-30)
```suggestion
## 12.0.0-beta.10 (2021-04-06)
```

2021-04-01 16:15 UTC, RickWinter commented on sdk/storage/azure-storage-files-shares/CHANGELOG.md
> +## 12.0.0-beta.10 (2021-03-30)
```suggestion
## 12.0.0-beta.10 (2021-04-06)
```

2021-04-08 05:25 UTC, closed without merging