Add George as reviewer
Azure/azure-sdk-for-cpp pull request #2494
Opened 2021-06-25 17:11 UTC by vhvb1989

Adding George as code owner so he become reviewer automatically

2021-06-25 22:02 UTC, ahsonkhan approved these changes

2021-06-25 22:03 UTC, ahsonkhan commented on .github/CODEOWNERS
> +/sdk/storage/            @vinjiang @katmsft @Jinming-Hu @antkmsft @rickwinter @vhvb1989 @gearana
@gearama let me know if this looks good.

2021-06-25 22:03 UTC, ahsonkhan commented on .github/CODEOWNERS
> +*                        @rickwinter @ahsonkhan @antkmsft @vhvb1989 @gearana
```suggestion
*                        @rickwinter @ahsonkhan @antkmsft @vhvb1989 @gearama
```

2021-06-25 22:04 UTC, ahsonkhan requested changes
Wrong GitHub alias, change everywhere: gearana -> gearama

2021-06-25 22:05 UTC, ahsonkhan commented on .github/CODEOWNERS
> +/sdk/storage/            @vinjiang @katmsft @Jinming-Hu @antkmsft @rickwinter @vhvb1989 @gearana
```suggestion
/sdk/storage/            @vinjiang @katmsft @Jinming-Hu @antkmsft @rickwinter @vhvb1989 @gearama
```

2021-06-28 09:17 UTC, antkmsft approved these changes

2021-06-28 15:43 UTC, RickWinter approved these changes

2021-06-28 15:46 UTC, RickWinter commented
/check-enforcer reset

2021-06-28 15:47 UTC, merged