reinterpret_cat_review inspection
Azure/azure-sdk-for-cpp pull request #2710
Opened 2021-08-04 21:34 UTC by vhvb1989

Bringing to the Team's attention the list of reinterpret_cast usages as part of:
https://github.com/Azure/azure-sdk-for-cpp/issues/2416

I am introducing a new document for the repo where all the current casting usages are recorded. We can decide if any of these casts should not be happening and fix as part of this PR.

The audit covers only src code. No tests/samples or external 3rd party source (like json lib) is covered.

2021-08-04 21:37 UTC, vhvb1989 commented on doc/CastingTypes.md
> +## reinterpret cast
@CaseyCarter  can you help me to review below list of type castings and mention if there is any of them which should not be done and re-designed?  (specially for the ones as `ToBeConfirmed`

2021-08-05 02:00 UTC, Jinming-Hu commented
@vhvb1989 Will pipeline help us check new castings introduced in every PR?

2021-08-09 17:48 UTC, vhvb1989 commented
> @vhvb1989 Will pipeline help us check new castings introduced in every PR? Like if a new casting isn't in `doc/CastingTypes.md`, CI will fail

I'd like that eventually. For now, it won't. It will only help us to make the first inspection to what we have.  You know, one step at a time

2021-08-11 07:31 UTC, antkmsft requested changes
I am sorry Victor, I've seen this PR, and you made a great effort identifying all cases and bringing in this organized doc, but I am not on board with the direction of this change, as well as some others, as we discussed during our standup.
I would suggest this:
1. Places are reviewed. That is technically good enough.
2. Better is to have a comment in the code, right next to the cast, at least oin some places where the cast is not obvious. Bonus - the comment is right next to the cast, it can be updated at once, and you don't have this level of indirection where you have to look it up in the doc, update/maintain the doc and so on.

So the comment would sometimes say things like `// Ok to cast since char and uint8_t are the same size`. Sometimes (and better often than not), it would have a corresponding `static_assert` next to it: `static_assert(sizeof(char) == sizeof(uint8_t))`.

And sometimes it is just impossible to explain why it is safe to `reinterpret_cast` the Azure::Context value while using just one line of comment, without writing an one pager. That is fine too, I think. Then we don't comment it. The reader will read the class code and see that it should be safe. Or maybe sees that it is not safe, and then will file a bug. But having a comment won't prevent us from having a bug there, anyways. It is not enforcing anything. It is obvious that if we have a `reinterpret_cast` there, we do believe to our best understanding of the matter, that that cast is safe and is the only way to achieve that we were trying to do. If anything, having a comment may give a false sense of security.

And 3rd thing that I would ask you to do is to see
* if in some places `static_cast` is needed at all. Maybe it was needed during the development, but now things are fine with just implicit casts.
* if in some places, `dynamic_cast` can be replaced with `static_cast` without any overhead and any risk (basically, in cases when `dynamic_cast` is guaranteed to always succeed, so simply not necessary)
* If in some places `const_cast` is no longer necessary, because we could've moved things around since the time it was put there. It is a better design to avoid const_casts, because it normally leads to a more streamlined design, and the code does not crash, should compiler decide to allocate a read-only object into a read-only memory. `mutable` modifier could be used on some cases where it is not possible to get rid of `const_cast` - at least it tells the compiler in a direct way that we do intend change the thing even from const instances.

2021-08-12 18:11 UTC, vhvb1989 commented
@antkmsft  the `comment every occurrence` does not feel nice to me.  We might be ending with many duplicated comments (as there are some typical casting cases).  And it is also a super fragile solution, it would be almost the same as doing nothing because: 
 - There will be always a chance to merge a `cast` without a comment/study
 - A comment/study might be wrong.

I think that if we want to consider `casting` something relevant, we have to plan and come up with something scalable and in a way that it can be automated in CI checks.  I would like to see us in a path where we want to auto-detect any `type casting` that is new in the source.  But of course, that is if we want to consider this as a priority/relevant subject. If not, I am happy to just leave it as it is and close the issue :)

2021-08-17 17:32 UTC, vhvb1989 commented
Decided to end the effort after a simple review-inspection of the type-casting

2021-08-17 17:32 UTC, closed without merging