Require Azure Core 1.3.1 for KeyVault packages
Azure/azure-sdk-for-cpp pull request #3101
Opened 2021-11-11 22:01 UTC by vhvb1989

fixes: https://github.com/Azure/azure-sdk-for-cpp/issues/3048

2021-11-12 05:28 UTC, ahsonkhan commented on sdk/keyvault/azure-security-keyvault-certificates/vcpkg/Config.cmake.in
> +find_dependency(azure-core-cpp "1.3.1")
I don't think this change alone is enough.

I think you'll also need to modify the json file:
https://github.com/Azure/azure-sdk-for-cpp/blob/9b4672be9324f218ecdedfe85cae184a59e2e482/sdk/keyvault/azure-security-keyvault-secrets/vcpkg/vcpkg.json#L17

cc @antkmsft, @ras0219-msft

2021-11-12 05:28 UTC, ahsonkhan requested changes
Looks good, but currently incomplete.

2021-11-15 17:07 UTC, RickWinter approved these changes

2021-11-15 19:55 UTC, ahsonkhan approved these changes

2021-11-15 21:35 UTC, merged