Organize applying Identity log prefix
Azure/azure-sdk-for-cpp pull request #4459
Opened 2023-03-16 22:57 UTC by antkmsft

Closes #4451.

2023-03-20 17:03 UTC, RickWinter requested changes
Rather than adding a class in every package, we should standardize the log output message to append the package name to each message.
That way customers could do filtering in ways similar to other Azure SDKs.  

See below for .NET as an example
```
if (args.EventSource.Name.StartsWith("Azure-Identity") && args.Level == EventLevel.Verbose)
    {
        Trace.WriteLine(message);
    }
    else if (args.EventSource.Name.StartsWith("Azure-Messaging-EventHubs"))
    {
        switch (args.EventId)
        {
            case 3:   // Event Publish Start
            case 4:   // Event Publish Complete
            case 5:   // Event Publish Error
                Console.WriteLine(message);
                break;
        }
    }
```

2023-03-22 21:28 UTC, RickWinter commented on sdk/identity/azure-identity/src/private/identity_log.hpp
> +      Core::Diagnostics::_internal::Log::Write(level, "Identity: " + message);
```suggestion
      Core::Diagnostics::_internal::Log::Write(level, "[azure-identity] " + message);
```

2023-03-22 21:28 UTC, RickWinter approved these changes

2023-03-22 21:46 UTC, antkmsft commented on sdk/identity/azure-identity/src/private/identity_log.hpp
> +      Core::Diagnostics::_internal::Log::Write(level, "Identity: " + message);
#4475

2023-03-22 21:46 UTC, merged