Amqp gearama2
Azure/azure-sdk-for-cpp pull request #4571
Opened 2023-04-24 20:38 UTC by gearama

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2023-04-24 20:39 UTC, gearama commented
/azp run cpp - eventhubs - ci

2023-04-25 06:39 UTC, LarryOsterman approved these changes

2023-06-13 01:47 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/vcpkg/Config.cmake.in
> +find_dependency(azure-core-cpp "1.9.0")
```suggestion
find_dependency(azure-core-cpp "1.9.0")
find_dependency(azure-core-amqp-cpp)
```

2023-06-13 01:47 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/CMakeLists.txt
> +  endif()
```suggestion
  find_package(azure-core-cpp "1.9.0" CONFIG QUIET)
  if(NOT azure-core-cpp_FOUND)
    find_package(azure-core-cpp "1.9.0" REQUIRED)
  endif()
  
  find_package(azure-core-amqp-cpp CONFIG QUIET)
  if(NOT azure-core-amqp-cpp_FOUND)
    find_package(azure-core-amqp-cpp REQUIRED)
  endif()
  
  find_package(azure-storage-blobs-cpp "12.7.0" CONFIG QUIET)
  if(NOT azure-core-cpp_FOUND)
    find_package(azure-storage-blobs-cpp "12.7.0" REQUIRED)
  endif()
```

2023-06-13 01:47 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/CMakeLists.txt
> +)
```suggestion
```

2023-06-13 01:47 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/CMakeLists.txt
> +unset(FETCH_SOURCE_DEPS CACHE)
```suggestion
unset(FETCH_SOURCE_DEPS CACHE)

```

2023-06-13 19:06 UTC, antkmsft commented on cmake-modules/FolderList.cmake
> +        DownloadDepVersion(sdk/storage/azure-storage-common azure-storage-common 12.3.1)
```suggestion
    elseif(${project} STREQUAL MESSAGING)
        DownloadDepVersion(sdk/core azure-core 1.8.0)
        DownloadDepVersion(sdk/core azure-core-amqp)
        DownloadDepVersion(sdk/storage/azure-storage-common azure-storage-common 12.3.1)
```

2023-06-13 22:38 UTC, RickWinter commented on CMakeSettings.json
> +      "cmakeToolchain": "D:/vcpkg/scripts/buildsystems/vcpkg.cmake"
Don't hardcode the path.

2023-06-13 22:41 UTC, RickWinter commented on sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/models/amqp_message.hpp
> +}}}} // namespace Azure::Messaging::EventHubs::Models
```suggestion
}}}} // namespace Azure::Messaging::EventHubs::Models

```

2023-06-15 00:15 UTC, LarryOsterman requested changes
Taking a break from the PR now, but I have a bunch of stuff here :).

2023-06-15 19:48 UTC, antkmsft reviewed
I have not gone through every occurrence, but search the code for "ID" case sensitive, they should be changed to "Id".
ID - is not an abbreviation, and we use "Id" in all other places in the SDK.

2023-06-15 19:48 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/consumer_client.hpp
> +        std::string const& partitionID,
```suggestion
        std::string const& partitionId,
```

2023-06-15 19:48 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/event_data_batch.hpp
> +    std::string m_partitionID;
```suggestion
    std::string m_partitionId;
```

2023-06-15 19:48 UTC, antkmsft commented on sdk/eventhubs/azure-messaging-eventhubs/inc/azure/messaging/eventhubs/event_data_batch.hpp
> +    void SetPartitionID(std::string partitionID) { m_partitionID = partitionID; }
```suggestion
    void SetPartitionId(std::string const& partitionId) { m_partitionID = partitionID; }
```

2023-06-26 23:32 UTC, LarryOsterman commented
/azp run cpp - eventhubs - ci

2023-07-05 19:08 UTC, LarryOsterman commented
/azp run cpp - azure-messaging-eventhubs - ci

2023-07-06 00:16 UTC, closed without merging