Storage/STG90-Data Lake Pagination Delete
Azure/azure-sdk-for-cpp pull request #4816
Opened 2023-07-24 07:54 UTC by microzchang

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2023-07-24 08:36 UTC, Jinming-Hu requested changes

2023-07-24 08:38 UTC, microzchang commented on sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_path_client.hpp
> +    _detail::DatalakeClientConfiguration m_clientConfiguration;
Ok. I will add this to all clients in datalake.

2023-07-25 05:30 UTC, Jinming-Hu requested changes

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/inc/azure/storage/files/datalake/datalake_path_client.hpp
> +          m_pipeline(std::move(pipeline)), m_clientConfiguration(clientConfiguration)
```suggestion
          m_pipeline(std::move(pipeline)), m_clientConfiguration(std::move(clientConfiguration))
```

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_file_system_client.cpp
>          builder,
```suggestion
        std::move(builder),
```

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
> +        && m_clientConfiguration.TokenCredential != nullptr;
```suggestion
        && m_clientConfiguration.TokenCredential;
```

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
> +        && m_clientConfiguration.TokenCredential != nullptr;
I think we can use the built-in `operator bool` converter.

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
> +        && m_clientConfiguration.TokenCredential != nullptr;
https://en.cppreference.com/w/cpp/memory/shared_ptr/operator_bool

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
> +    std::string continuationToken = "";
```suggestion
    std::string continuationToken;
```

2023-07-25 05:30 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-datalake/src/datalake_path_client.cpp
> +    do
It's considered a bad practice to use `do while` loops in some style guides. Some formatter would emit a warning.

https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-do

2023-07-25 05:50 UTC, Jinming-Hu approved these changes

2023-07-27 14:02 UTC, Jinming-Hu approved these changes

2023-07-28 06:21 UTC, microzchang commented
/azp run cpp -storage

2023-07-28 06:21 UTC, microzchang commented
/azp run cpp - storage

2023-07-28 07:22 UTC, merged