Storage/File Share test improvement
Azure/azure-sdk-for-cpp pull request #4885
Opened 2023-08-15 08:47 UTC by microzchang

# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2023-08-15 08:49 UTC, microzchang commented
It's really difficult to test file handles...

2023-08-16 02:34 UTC, Jinming-Hu requested changes

2023-08-16 02:34 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-shares/test/ut/share_sas_test.cpp
> +    void VerifyDataLakeSasRead(
This is not datalake, it's file share

2023-08-16 02:34 UTC, Jinming-Hu commented on sdk/storage/azure-storage-files-shares/test/ut/share_sas_test.cpp
> +    void VerifyDataLakeSasMove(
Does share service support moving file?

2023-08-16 02:41 UTC, Jinming-Hu approved these changes

2023-08-16 03:08 UTC, microzchang commented
/azp run cpp - storage

2023-08-16 04:20 UTC, microzchang commented
/azp run cpp - storage

2023-08-16 05:02 UTC, microzchang commented
/azp run cpp - storage

2023-08-16 05:22 UTC, microzchang commented
/azp run cpp - storage

2023-08-16 06:04 UTC, merged