Updated changelog for azure core amqp and eventhubs around mentions of ostream operators
Azure/azure-sdk-for-cpp pull request #5082
Opened 2023-10-28 00:18 UTC by ahsonkhan

Following-up from https://github.com/Azure/azure-sdk-for-cpp/pull/5060#discussion_r1372399248

For reference, this diff shows the comparison of what was previously shipped vs what's in main now:
https://github.com/Azure/azure-sdk-for-cpp/compare/azure-messaging-eventhubs_1.0.0-beta.3...main

The additions to AMQP were in `_detail` namespace

2023-10-28 00:46 UTC, antkmsft approved these changes
I agree with the change, but let's get @LarryOsterman's ultimate word on this - he is the owner.
As of the AMQP changelog, I think in #5079, he drops that line.
Personally, for AMQP, I liked the "expanded logging coverage" line that I was proposing at a time :)

2023-10-30 16:53 UTC, LarryOsterman requested changes
Please undo the changes to AMQP.

And the vague wording around insertion operators was intentional. Please restore it (because there may be more changes made before the release as I integrate more fixes and that means we don't need to update the changelog entry).

2023-10-30 18:44 UTC, ahsonkhan commented
> Please undo the changes to AMQP.

How come? Is it because you are already doing that change in another PR?

2023-10-30 18:45 UTC, ahsonkhan commented
> And the vague wording around insertion operators was intentional. Please restore it (because there may be more changes made before the release as I integrate more fixes and that means we don't need to update the changelog entry).

Do you mean for eventhubs? So are you essentially suggeting we close this PR?

2023-10-31 17:36 UTC, LarryOsterman commented
> > Please undo the changes to AMQP.
> 
> How come? Is it because you are already doing that change in another PR?

Yes.

2023-10-31 17:36 UTC, LarryOsterman commented
> > And the vague wording around insertion operators was intentional. Please restore it (because there may be more changes made before the release as I integrate more fixes and that means we don't need to update the changelog entry).
> 
> Do you mean for eventhubs? So are you essentially suggeting we close this PR?

I don't have a problem with the PR as long as it is not specific about what was added. If you have a better wording for the change, that is fine.

2023-11-02 01:11 UTC, ahsonkhan commented
In that case, closing.

2023-11-02 01:11 UTC, closed without merging