Log policy extra headers
Azure/azure-sdk-for-cpp pull request #5868
Opened 2024-08-01 19:12 UTC by gearama

#closes #5782
Per customer request adding a few extra headers in the log 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2024-08-01 19:25 UTC, antkmsft requested changes
Is `WWW-Authenticate` safe to log by default? Do other SDKs log it? What has motivated this change, can you give more context? Should this be in the global list, or should some client library (Tables, for example) use this list only for its client? Does this PR syncs this list with some other language SDK? Where did you get these new headers from, why these headers?
Also, probably not the change to be merged before today's release is out.
Would customer be unblocked if they'd add these headers to the client options (`options.Log.AllowedHttpHeaders.insert()`), maybe they didn't know they could do that?

2024-08-01 19:34 UTC, gearama commented
> Is `WWW-Authenticate` safe to log by default? Do other SDKs log it? What has motivated this change, can you give more context? Should this be in the global list, or should some client library (Tables, for example) use this list only for its client? Does this PR syncs this list with some other language SDK? Where did you get these new headers from, why these headers? Also, probably not the change to be merged before today's release is out. Would customer be unblocked if they'd add these headers to the client options (`options.Log.AllowedHttpHeaders.insert()`), maybe they didn't know they could do that?

This change si by customer request , .Net and Java log the same header :
WWW-Authenticate is included in .NET and Java SDKs here:

.NET: https://github.com/Azure/azure-sdk-for-net/blob/main/sdk/core/Azure.Core/src/DiagnosticsOptions.cs#L44
Java: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/core/azure-core/src/main/java/com/azure/core/http/policy/HttpLogOptions.java#L69

2024-08-01 20:48 UTC, antkmsft commented
Sorry, it looks like I freaked out for no reason, and it is my fault for not reading the linked item. I think the change is likely ok, just let me to re-review it later, after we cut today's Core release, it will make it to the next one. Especially if we can double-confirm with the identity v-team that "WWW-Authenticate" is ok to log by default.

2024-08-01 21:45 UTC, gearama commented
> WWW-Authenti
Based on Conversation Ahson had with the Identity SDK v-team it is ok to lok this header as it is sent to unauthorized clients. 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate

2024-08-01 22:09 UTC, RickWinter reviewed
Please add a CHANGELOG entry after we cut this months release.

Looks good other than that.

2024-08-01 22:16 UTC, LarryOsterman approved these changes

2024-08-01 22:50 UTC, antkmsft approved these changes

2024-08-01 23:09 UTC, gearama commented
> Please add a CHANGELOG entry after we cut this months release.
> 
> Looks good other than that.

True that, i'll do it Fryday to give time for the release

2024-08-02 23:16 UTC, ahsonkhan approved these changes

2024-08-05 18:26 UTC, ahsonkhan commented on sdk/core/azure-core/CHANGELOG.md
> +- Request logs to now include the `accept-range`, `content-range`,`range`,`WWW-Authenticate`, `xx-ms-date`,`x-ms-error-code`,`x-ms-range`  and `x-ms-version` headers.
consistency nit: add a new line between heading and text (vscode markdown linter also complains about this)

```suggestion

- Request logs to now include the `accept-range`, `content-range`,`range`,`WWW-Authenticate`, `xx-ms-date`,`x-ms-error-code`,`x-ms-range`  and `x-ms-version` headers.
```

2024-08-07 17:40 UTC, merged