Tables readme update
Azure/azure-sdk-for-cpp pull request #5940
Opened 2024-08-27 19:40 UTC by gearama

closes #5906 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2024-08-28 21:30 UTC, ronniegeraghty commented
Missing these link references at the bottom: 
[azure_sub]: https://azure.microsoft.com/free/
[azure_cli]: https://docs.microsoft.com/cli/azure

2024-09-03 18:01 UTC, ronniegeraghty requested changes

2024-09-04 20:11 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +az <service-name> create --resource-group <your-resource-group-name> --name <your-<service-name>-name>
done

2024-09-04 20:12 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +vcpkg add port azure-<service-name>-cpp azure-identity-cpp
done

2024-09-04 20:13 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +az <service-name> create --resource-group <your-resource-group-name> --name <your-<service-name>-name>
maybe, i don't know how from cli, i only used the portal

2024-09-04 20:14 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +* [Table Transactions Error](#table-transactions-error "Table Transactions Error")
done

2024-09-04 20:15 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +
it is , on line below

2024-09-04 20:15 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +
line 191

2024-09-04 20:17 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +   AzureClientType client = clientCtor(url, credential);
it's in the tests , or in the samples. nobody reads these anyway.

2024-09-04 20:18 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +using namespace Azure::<Service::Name>;
done

2024-09-04 20:19 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
>  az storage account show -n mystorageaccount -g MyResourceGroup --query "primaryEndpoints.table"
i don't see it

2024-09-04 20:20 UTC, gearama commented on sdk/tables/azure-data-tables/README.md
> +We'll be using the `DefaultAzureCredential` to authenticate which will pick up the credentials we used when logging in with the Azure CLI earlier. `DefaultAzureCredential` can pick up on a number of
it works as i have done the transition of the tests myself

2024-09-05 19:15 UTC, ronniegeraghty approved these changes

2024-09-05 20:06 UTC, ronniegeraghty approved these changes

2024-09-05 20:13 UTC, merged