Kv doc update
Azure/azure-sdk-for-cpp pull request #5946
Opened 2024-08-28 19:52 UTC by gearama

closes #5898 
closes #5899 
closes #5900
closes #5901 
# Pull Request Checklist

Please leverage this checklist as a reminder to address commonly occurring feedback when submitting a pull request to make sure your PR can be reviewed quickly:

See the detailed list in the [contributing guide](https://github.com/Azure/azure-sdk-for-cpp/blob/main/CONTRIBUTING.md#pull-requests).

- [ ] [C++ Guidelines](https://azure.github.io/azure-sdk/cpp_introduction.html)
- [ ] Doxygen docs
- [ ] Unit tests
- [ ] No unwanted commits/changes
- [ ] Descriptive title/description
  - [ ] PR is single purpose
  - [ ] Related issue listed
- [ ] Comments in source
- [ ] No typos
- [ ] Update changelog
- [ ] Not work-in-progress
- [ ] External references or docs updated
- [ ] Self review of PR done
- [ ] Any breaking changes?

2024-08-28 21:21 UTC, ronniegeraghty commented
Before the first Azure CLI command (line 24) add the `az login` command just as a note that it's needed and that the AzureDefaultCrednetial will use it.

2024-09-04 20:23 UTC, gearama commented on sdk/keyvault/azure-security-keyvault-administration/README.md
>  For detailed samples please review the code provided.
we use them all over the place it gives an idea that here be samples

2024-09-05 18:48 UTC, ronniegeraghty requested changes

2024-09-05 18:48 UTC, ronniegeraghty commented on sdk/keyvault/azure-security-keyvault-certificates/README.md
> +```CMake
```suggestion
```CMake
find_package(azure-identity-cpp CONFIG REQUIRED)
```

2024-09-05 18:48 UTC, ronniegeraghty commented on sdk/keyvault/azure-security-keyvault-administration/README.md
> +he easiest way to acquire the C++ SDK is leveraging the vcpkg package manager and CMake. See the corresponding [Azure SDK for C++ readme section][azsdk_vcpkg_install]. We'll use vcpkg in manifest mod
```suggestion
The easiest way to acquire the C++ SDK is leveraging the vcpkg package manager and CMake. See the corresponding [Azure SDK for C++ readme section][azsdk_vcpkg_install]. We'll use vcpkg in manifest mode. To start a vcpkg project in manifest mode use the following command at the root of your project: 
```

2024-09-05 18:48 UTC, ronniegeraghty commented on sdk/keyvault/azure-security-keyvault-keys/README.md
> +```CMake
```suggestion
```CMake
find_package(azure-identity-cpp CONFIG REQUIRED)
```

2024-09-05 19:16 UTC, ronniegeraghty approved these changes

2024-09-05 20:13 UTC, merged