Do not reuse a connection that fail while uploading
Azure/azure-sdk-for-cpp pull request #863
Opened 2020-10-27 06:00 UTC by vhvb1989

The issue is that if that if a connection throw while reading from the server, when we check if it is EOF (contentLenght == session.totalRead) is true because we don't know the content length yet.  
We need to introduce an internal state to check this case and do not move the connection back to the connection pool.

Right now, the connection is moved back to the pool and will fail every time we try to reuse that connection.

fixes: https://github.com/Azure/azure-sdk-for-cpp/issues/815

2020-10-27 06:08 UTC, Jinming-Hu commented
@vhvb1989 So you figured out the problem without being able to reproduce it? good job!

2020-10-27 07:01 UTC, Jinming-Hu requested changes
Please hold on merging until I finish validation

2020-10-27 07:02 UTC, vhvb1989 commented
> Please hold on merging until I finish validation

Sure, 
Still need to add to changelog and try to add one test at least

2020-10-28 01:50 UTC, Jinming-Hu approved these changes
it should work. I'll do more tests in the future. Let's merge this PR.

2020-10-28 08:27 UTC, merged

2020-10-28 08:28 UTC, vhvb1989 commented
test are pending for now.
I need to make some refactoring in the curl transport adapter to be able to mock the curl connection and fake this error

2020-11-05 20:20 UTC, ahsonkhan commented on sdk/core/azure-core/CHANGELOG.md
> +- Avoid re-using a connection when an uploading request fail when using CurlTransport.
```suggestion
- Avoid re-using a connection when a request to upload data fails while using the `CurlTransport`.
```

2020-11-05 20:55 UTC, ahsonkhan commented
>test are pending for now.

Issue please.

2020-11-05 21:35 UTC, vhvb1989 commented
> 
> 
> > test are pending for now.
> 
> Issue please.

https://github.com/Azure/azure-sdk-for-cpp/issues/905