update license to be just one in root repo and with txt
Azure/azure-sdk-for-cpp pull request #888
Opened 2020-10-30 23:48 UTC by vhvb1989

fixes: https://github.com/Azure/azure-sdk-for-cpp/issues/887

2020-11-02 17:03 UTC, RickWinter requested changes
If we do this change we need to alter our packaging scripts to ensure each package includes the liscense.

2020-11-04 01:05 UTC, vhvb1989 commented
> 
> 
> If we do this change we need to alter our packaging scripts to ensure each package includes the license.

The License is linked in all the Readme files from each package.
This is how all the other languages are doing.
When we release, we will keep the root files right?  (License, Notice, etc.)   The License is always at the root, and each package links to it since it is the same

2020-11-04 01:34 UTC, vhvb1989 commented
/check-enforcer override

2020-11-04 17:01 UTC, RickWinter approved these changes

2020-11-04 17:03 UTC, merged