Added contribution.md
Azure/azure-sdk-for-cpp pull request #913
Opened 2020-11-06 10:40 UTC by katmsft

WIP, please review and raise your valuable comments.

2020-11-06 18:06 UTC, RickWinter requested changes
There is a general contributing.md at the root of the repo.  To avoid duplication of a lot of content we link to that from package readmes.  
Please link to that in your README.md.  see https://github.com/Azure/azure-sdk-for-cpp/tree/master/sdk/core/azure-core#contributing for example pattern.  

Specific contributing instructions for you package can be added to you contributing section in the in your README.md.  Any contributing guidelins specific to all of the SDKs needs to be in the root contributing.md.

2020-11-09 14:00 UTC, katmsft commented
I don't know how to make the existing PR a draft, so I'll close this PR for now and make this change to README instead.

2020-11-09 14:02 UTC, closed without merging

2020-11-09 18:40 UTC, ahsonkhan commented
@katmsft, here is how you can turn a PR into a draft:
![image](https://user-images.githubusercontent.com/6527137/98582520-eb5b1680-2277-11eb-850c-bc65c62866d6.png)

> Still in progress? Convert to draft

2020-11-09 19:07 UTC, ahsonkhan commented on sdk/storage/CONTRIBUTION.md
> +Please let the team know if you have any questions or concerns about our contribution policy.
This part of the doc is unnecessary/redundant and can be removed.

2020-12-10 23:47 UTC, ahsonkhan commented on sdk/storage/CONTRIBUTION.md
> +Please login and go to [this page](https://ms.portal.azure.com/#blade/Microsoft_AAD_RegisteredApps/ApplicationsListBlade) to create register an application.
Add notes about how to setup all the required fields here along with sample screenshots of azure portal, so it is easier to understand where things like `Storage Blob Data Owner` are supposed to go.

For example what should the "Role" and "Assign access to" fields be set to?

2020-12-10 23:47 UTC, ahsonkhan commented on sdk/storage/CONTRIBUTION.md
> +You can leverage [this doc](https://docs.microsoft.com/en-us/azure/storage/blobs/create-data-lake-storage-account) to create storage account to run test cases for DataLake Gen2 service.
What specific section in the linked doc is relevant to this task? Please update all the links that point to large multi-section docs, to point to the exact relevant section, or at least name the section title in the url-text.

2020-12-10 23:47 UTC, ahsonkhan commented
@katmsft - this document was quite useful. Do you plan to revisit this PR in the future and have this info checked-in?